name: Auto PR for Codex branches

on:
  push:
    branches:
      - 'codex/**'
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: codex-pr-${{ github.ref }}
  cancel-in-progress: false

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: meta
        run: |
          ref="${GITHUB_REF##refs/heads/}"
          echo "branch=$ref" >> "$GITHUB_OUTPUT"

      - name: Create or update PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = process.env.BRANCH || `${{ steps.meta.outputs.branch }}`;
            const base = process.env.BASE || 'main';
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Check if a PR from this branch to base already exists
            const prs = await github.paginate(github.rest.pulls.list, {
              owner, repo, state: 'open', head: `${owner}:${branch}`, base
            });

            if (prs.length > 0) {
              core.info(`PR already exists: ${prs[0].html_url}`);
              return;
            }

            const title = `Codex: ${branch}`;
            const body = [
              'Automated PR created from Codex Web branch.',
              '',
              `Branch: \`${branch}\``,
              `Base: \`${base}\``
            ].join('\n');

            const { data: pr } = await github.rest.pulls.create({
              owner, repo, title, head: branch, base, body
            });

            core.info(`Created PR: ${pr.html_url}`);

            // Try to add a label if it exists
            try {
              await github.rest.issues.addLabels({
                owner, repo, issue_number: pr.number, labels: ['codex']
              });
            } catch (e) {
              core.info('Label add skipped (label may not exist).');
            }

